export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDENT = "REMOVE_INGREDENT";
export const SET_INGREDENT = "SET_INGREDENT";
export const FETCH_INGREDENT_FAIELD = "FETCH_INGREDENT_FAIELD";

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_INIT = "PURCHASE_BURGER_INIT";

export const FETCH_ORDERS_INIT_START = "FETCH_ORDERS_INIT_START";
export const FETCH_ORDERS_INIT_SUCCESS = "FETCH_ORDERS_INIT_SUCCESS";
export const FETCH_ORDERS_INIT_FAILED = "FETCH_ORDERS_INIT_FAILED";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
